config/routes.rb
RepoFollow::Application.routes.draw do
  root to: 'home#index'

  # Sessions/Authentication
  get '/auth/github/callback', to: 'sessions#create'
  get '/sign_up', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'

  # Github
  get '/github/public_repos', to: 'github#public_repos'

  # Repos
  post '/repos/follow', to: 'repos#follow'
  post '/repos/unfollow', to: 'repos#unfollow'
  resources :repos, only: [:index, :edit] do
    post '/unfollow_branch', to: 'repos#unfollow_branch'
    post '/follow_branch', to: 'repos#follow_branch'
  end
end

app/models/repo.rb
class Repo < ActiveRecord::Base
  attr_accessible :full_name, :github_uid, :name

  validates_presence_of :github_uid

  validates_uniqueness_of :github_uid

  has_many :follow_repos
  has_many :followers, class_name: 'User', source: :user, through: :follow_repos

  has_many :branches
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  include GithubHelper

  def follow
    @repo = Repo.where(github_uid: params[:github_uid]).first
    load_git_repo! unless @repo

    follow = FollowRepo.new
    follow.repo = @repo
    follow.user = current_user

    if follow.save
      render json: {}, status: :ok
    else
      render json: {errors: follow.errors}
    end
  end

  def unfollow
    @repo = Repo.where(github_uid: params[:github_uid]).first
    load_git_repo! unless @repo

    follow = FollowRepo.where(repo_id: @repo.id, user_id: current_user.id).first

    unless follow.nil? || follow.destroy
      flash_message(:error, "Unable to stop following repository: #{@repo.full_name if @repo}")
    end
    redirect_to repos_path
  end

  def follow_branch
    @repo = Repo.find(params[:repo_id])

    branch = Branch.where(repo_id: @repo.id, name: params[:branch_name]).first_or_create

    unfollow = UnfollowBranch.where(branch_id: branch.id, user_id: current_user.id).first

    unless unfollow.nil? || unfollow.destroy
      flash_message(:error, "Could not follow branch: #{branch.name if branch}")
    end

    invalidate_cache_commits(@repo.full_name, nil, true)
    redirect_to edit_repo_path(@repo)
  end

  def unfollow_branch
    @repo = Repo.find(params[:repo_id])

    branch = Branch.where(repo_id: @repo.id, name: params[:branch_name]).first_or_create

    unfollow = UnfollowBranch.new(branch_id: branch.id)
    unfollow.user = current_user

    unless unfollow.save
      flash_message(:error, "Could not unfollow branch: #{branch ? branch.name : ''}")
    end

    invalidate_cache_commits(@repo.full_name, nil, true)
    redirect_to edit_repo_path(@repo)
  end

  def index
    @repos = current_user.followed_repos
    render 'index'
  end

  def edit
    @repo = Repo.find(params[:id])
    @branches = load_git_repo_branches!(@repo)
    @followed_branches = @branches - current_user.unfollowed_branches
    @unfollowed_branches = @branches - @followed_branches
    # TODO as an optimization, we could maintain a has_unfollowed_branches boolean on FollowRepo and only query branch following or activity scoping if it's true
    render 'edit'
  end

end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/repos/edit.html.slim
h2.repo-title= @repo.full_name
= form_tag(repos_unfollow_path, class: 'form-inline') do
  input type="hidden" name="github_uid" value="#{@repo.github_uid}"
  input type="submit" value="unfollow repository" class="button-link"

h3 Followed Branches:
ul.followed-branches
  - @followed_branches.each do |branch|
    li
      = branch.name
      = form_tag(repo_unfollow_branch_path(@repo), class: 'form-inline') do
        input type="hidden" name="branch_name" value="#{branch.name}"
        input type="submit" value="unfollow" class="button-link"
hr
ul.unfollowed-branches
  - @unfollowed_branches.each do |branch|
    li
      = branch.name
      = form_tag(repo_follow_branch_path(@repo), class: 'form-inline') do
        input type="hidden" name="branch_name" value="#{branch.name}"
        input type="submit" value="follow" class="button-link"

app/views/repos/index.html.slim
h1 My Followed Repositories

ul
  - @repos.each do |repo|
    li = link_to repo.full_name, edit_repo_path(repo)