config/routes.rb
RepoFollow::Application.routes.draw do
  root to: 'home#index'

  # Sessions/Authentication
  get '/auth/github/callback', to: 'sessions#create'
  get '/sign_up', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'

  # Github
  get '/github/public_repos', to: 'github#public_repos'

  # Repos
  post '/repos/follow', to: 'repos#follow'
  post '/repos/unfollow', to: 'repos#unfollow'
  resources :repos, only: [:index, :edit] do
    post '/unfollow_branch', to: 'repos#unfollow_branch'
    post '/follow_branch', to: 'repos#follow_branch'
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RepoFollow
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    header
      .ym-wrapper
        .ym-wbox
          .nav.ym-hlist
            - if current_user
              ul
                li= link_to "Feed", root_path
                li= link_to "Browse Repos", github_public_repos_path
                li= link_to "My Repos", repos_path
              .user-nav
                span.user-name
                  = current_user.display_name
                span.sign-out-link
                  = link_to "Sign Out", sign_out_path

    section
      .ym-wrapper
        .ym-wbox
          - flash.each do |type, messages|
            - if messages.present?
              div class="#{type}"
                - messages.each do |message|
                  p= message

          = yield

    footer
      .ym-wrapper
        .ym-wbox